name = "MagneticSkyrmions"
uuid = "7c82cc0f-3a53-477d-b16f-e55d9bbbf837"
authors = ["Chris Halcrow"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
